VERSION 0.6

FROM golang:1.17-alpine
RUN apk --update --no-cache add git
WORKDIR /go-example

all:
    BUILD +lint
    BUILD +build
    BUILD +docker

lint:
    COPY main.go go.mod .
    RUN go vet ./...

staticcheck:
    RUN go install honnef.co/go/tools/cmd/staticcheck@latest
    COPY main.go go.mod .
    RUN staticcheck ./...

build:
    #ENV GOOS=darwin
    #ENV GOARCH=arm64
    COPY main.go go.mod .
    RUN go build -o build/go-example main.go
    SAVE ARTIFACT build/go-example /go-example AS LOCAL build/go-example

docker:
    #BUILD +build # save file
    COPY +build/go-example .
    ENTRYPOINT ["/go-example/go-example"]
    SAVE IMAGE mario21ic/go-example:latest

